version: '3.8'

services:
  ctf-app:
    build: .
    container_name: flower-garden-ctf
    ports:
      - "4545:4545"
    environment:
      - FLAG=h3x1514{jwt_ny4shny_br3aker_uwu}
    restart: unless-stopped